from gym_v.envs.textarena.crosswords import TextArenaCrosswordsEnv
from gym_v.envs.textarena.fifteenpuzzle import TextArenaFifteenPuzzleEnv
from gym_v.envs.textarena.frozenlake import TextArenaFrozenLakeEnv
from gym_v.envs.textarena.game2048 import TextArenaGame2048Env
from gym_v.envs.textarena.lightsout import TextArenaLightsOutEnv
from gym_v.envs.textarena.minesweeper import TextArenaMinesweeperEnv
from gym_v.envs.textarena.pegjump import TextArenaPegJumpEnv
from gym_v.envs.textarena.rushhour import TextArenaRushHourEnv
from gym_v.envs.textarena.sokoban import TextArenaSokobanEnv
from gym_v.envs.textarena.sudoku import TextArenaSudokuEnv
from gym_v.envs.textarena.towerofhanoi import TextArenaTowerOfHanoiEnv
from gym_v.envs.textarena.wordle import TextArenaWordleEnv
from gym_v.envs.textarena.wordsearch import TextArenaWordSearchEnv
